[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "RugbugRedfern"
name = "MyceliumNetworking"
description = "An easy to use networking library for sending custom RPCs through Steam."
websiteUrl = "https://github.com/Dimolade/Mycelium-Networking-For-STRAFTAT"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../../LICENSE.txt"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/MyceliumNetworkingForCW.dll"
target = "/BepInEx/plugins/MyceliumNetworking/"

[publish]
communities = [ "straftat" ]
[publish.categories]
straftat = [ "libraries" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/straftat/category/
